### ISSUE TITLE
public atribut

### ISSUE THREAD

**Issue by MartinParak** [martindoro/Conways-Life#6]
Tento atribut je public, ale aj tak k nemu existuje getter a setter. Bud jedno, alebo druhe, Nevidim dovod, preco by mal byt public, ale ak mas nejaky dobry dovod, tak ho mozes nechat. Ale v tom pripade k nemu nepotrebujes G+S.

https://github.com/martindoro/Conways-Life/blob/4d223aa3d85ec7d6eab5ee96e82ffd5dd3efda3c/src/conways_life/RandomSliderPanel.java#L17

**Comment by martindoro** [comment]
done
