### ISSUE TITLE
GridLayout 1x1

### ISSUE THREAD

**Issue by MartinParak** [martindoro/Conways-Life#7]
mi nedava nejaky vyznam. GridLayout sa pouziva tam, kde mam zlozitejsi design. Ty si takto vytvoris grid o velkosti 1 prvok x 1 prvok. To nemusi byt grid. (Nie je to chyba, len je to zbytocne)

https://github.com/martindoro/Conways-Life/blob/4d223aa3d85ec7d6eab5ee96e82ffd5dd3efda3c/src/conways_life/RandomSliderPanel.java#L28

**Comment by martindoro** [comment]
ked odstranim gridlayout, tak slider nieje roztiahnuty po celej vyske okna a potom to nevyzera pekne, mozno este zajtra na to pozriem
