### ISSUE TITLE
tento if tu ani nemusi byt

### ISSUE THREAD

**Issue by MartinParak** [martindoro/Conways-Life#9]
mozes rovno nastavit bunku na true, bez skumania, ci predtym bola true. Usetris si tym jeden krok pri bunkach, ktore boli false.
Pri bunkach, ktore uz boli true vykonas jeden krok, ktory by si aj tak vykonal skumanim.

Takto ako to je, to nie je chyba, ide len o zrychlenie programu.

https://github.com/martindoro/Conways-Life/blob/4d223aa3d85ec7d6eab5ee96e82ffd5dd3efda3c/src/conways_life/CellsPanel.java#L69

**Comment by martindoro** [comment]
done
